name: Code Quality Checks

on:
  push:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get UID and GID
        id: user_info
        run: |
          echo "uid=$(id -u)" >> $GITHUB_OUTPUT
          echo "gid=$(id -g)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image - pinch-php
        uses: docker/build-push-action@v6
        with:
          context: ./packages/template
          file: ./packages/template/Dockerfile
          target: development-php
          build-args: |
            USER_UID=${{ steps.user_info.outputs.uid }}
            USER_GID=${{ steps.user_info.outputs.gid }}
          tags: |
            ghcr.io/${{ github.repository }}-php:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}-php:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha
          load: true

      - name: Build Image - pinch-web
        uses: docker/build-push-action@v6
        with:
          context: ./packages/template
          file: ./packages/template/Dockerfile
          target: development-web
          tags: |
            ghcr.io/${{ github.repository }}-web:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}-web:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha
          load: true

      - name: Build Image - pinch-prettier
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./packages/template/Dockerfile
          target: prettier
          tags: |
            ghcr.io/${{ github.repository }}-prettier:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}-prettier:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha
          load: true

      - name: Build Application
        run: |
          cp .env.dist .env;
          sed -i "s/^GITHUB_TOKEN=.*/GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}/" ".env";
          make -j

      - name: Run Code Quality Checks
        run: make ci;
