name: Code Quality Checks

on:
  push:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image - pinch-php
        uses: docker/build-push-action@v6
        with:
          context: ./packages/template
          file: ./packages/template/Dockerfile
          target: development-php
          tags: ghcr.io/${{ github.repository }}-php:latest # not pushed, just used locally
          cache-from: type=gha,scope=${{ github.repository }}-php
          cache-to: type=gha,scope=${{ github.repository }}-php,mode=max
          load: true

      - name: Build Image - pinch-web
        uses: docker/build-push-action@v6
        with:
          context: ./packages/template
          file: ./packages/template/Dockerfile
          target: development-web
          tags: ghcr.io/${{ github.repository }}-web:latest # not pushed, just used locally
          cache-from: type=gha,scope=${{ github.repository }}-web
          cache-to: type=gha,scope=${{ github.repository }}-web,mode=max
          load: true

      - name: Build Image - pinch-prettier
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./packages/template/Dockerfile
          target: prettier
          tags: ghcr.io/${{ github.repository }}-prettier:latest # not pushed, just used locally
          cache-from: type=gha,scope=${{ github.repository }}-prettier
          cache-to: type=gha,scope=${{ github.repository }}-prettier,mode=max
          load: true

      - name: Build Application
        run: |
          cp .env.dist .env;
          sed -i "s/^GITHUB_TOKEN=.*/GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}/" ".env";
          make -j

      - name: Run Code Quality Checks
        run: make ci;
